const CHARACTERS_DATA = [
    { id: 1, name: "ASTA", magic: "ANTI MAGIC", rank: "MAGIC KNIGHT" },
    { id: 2, name: "YUNO", magic: "WIND / STAR", rank: "MAGIC KNIGHT" },
    { id: 3, name: "NOELLE SILVA", magic: "WATER", rank: "MAGIC KNIGHT" },
    { id: 4, name: "YAMI SUKEHIRO", magic: "DARK", rank: "CAPTAIN" },
    { id: 5, name: "NACHT FAUST", magic: "SHADOW", rank: "VICE-CAPTAIN" },
    { id: 6, name: "NERO", magic: "SEALING", rank: "MAGIC KNIGHT" },
    { id: 7, name: "VANESSA ENOTECA", magic: "RED THREAD", rank: "MAGIC KNIGHT" },
    { id: 8, name: "LUCK VOLTIA", magic: "LIGHTNING", rank: "MAGIC KNIGHT" },
    { id: 9, name: "MAGNA SWING", magic: "FIRE", rank: "MAGIC KNIGHT" },
    { id: 10, name: "CHARMY PAPPITSON", magic: "COTTON / FOOD", rank: "MAGIC KNIGHT" },
    { id: 11, name: "FINRAL ROULACASE", magic: "SPATIAL", rank: "MAGIC KNIGHT" },
    { id: 12, name: "GAUCHE ADLAI", magic: "MIRROR", rank: "MAGIC KNIGHT" },
    { id: 13, name: "GREY", magic: "TRANSMUTATION", rank: "MAGIC KNIGHT" },
    { id: 14, name: "GORDON AGRIPPA", magic: "POISON CURSE", rank: "MAGIC KNIGHT" },
    { id: 15, name: "MIMOSA VERMILLION", magic: "PLANT", rank: "MAGIC KNIGHT" },
    { id: 16, name: "LEOPOLD VERMILLION", magic: "FIRE", rank: "MAGIC KNIGHT" },
    { id: 17, name: "FUEGOLEON VERMILLION", magic: "FIRE", rank: "CAPTAIN" },
    { id: 18, name: "MEREOLEONA VERMILLION", magic: "FIRE", rank: "CAPTAIN" },
    { id: 19, name: "CHARLOTTE ROSELEI", magic: "BRIAR", rank: "CAPTAIN" },
    { id: 20, name: "NOZEL SILVA", magic: "MERCURY", rank: "CAPTAIN" },
    { id: 21, name: "JULIUS NOVACHRONO", magic: "TIME", rank: "WIZARD KING" },
    { id: 22, name: "ZORA IDEALE", magic: "ASH / TRAP", rank: "MAGIC KNIGHT" },
    { id: 23, name: "HENRY LEGOLANT", magic: "RECOMBINATION", rank: "MAGIC KNIGHT" },
    { id: 24, name: "LIEBE", magic: "ANTI MAGIC", rank: "DEVIL" },
    { id: 25, name: "DANTE ZOGRATIS", magic: "BODY / GRAVITY", rank: "DARK TRIAD" },
    { id: 26, name: "VANICA ZOGRATIS", magic: "BLOOD", rank: "DARK TRIAD" },
    { id: 27, name: "ZENON ZOGRATIS", magic: "BONE / SPATIAL", rank: "DARK TRIAD" },
    { id: 28, name: "LOLOPECHKA", magic: "WATER", rank: "PRINCESS" },
    { id: 29, name: "RILL BOISMORTIER", magic: "PAINTING", rank: "CAPTAIN" },
    { id: 30, name: "DOROTHY UNSWORTH", magic: "DREAM", rank: "CAPTAIN" },
    { id: 31, name: "JACK THE RIPPER", magic: "SLASH", rank: "CAPTAIN" },
    { id: 32, name: "LANGRIS VAUDE", magic: "SPATIAL", rank: "VICE-CAPTAIN" },
    { id: 33, name: "WILLIAM VANGEANCE", magic: "WORLD TREE", rank: "CAPTAIN" },
    { id: 34, name: "PATRI", magic: "LIGHT", rank: "LEADER" },
    { id: 35, name: "LADROS", magic: "MANA ABSORB", rank: "DIAMOND MAGE" },
    { id: 36, name: "MARS", magic: "CRYSTAL / FIRE", rank: "DIAMOND MAGE" },
    { id: 37, name: "FANA", magic: "FIRE / HEALING", rank: "APOSTLE" },
    { id: 38, name: "VETTO", magic: "BEAST", rank: "APOSTLE" },
    { id: 39, name: "LICHT", magic: "SWORD / LIGHT", rank: "LEADER" },
    { id: 40, name: "HENRY SWALLOWTAIL", magic: "RECOMBINATION", rank: "MAGIC KNIGHT" },
];
